### ISSUE TITLE
Finds url's not linked to in my code and which return an error

### ISSUE THREAD

**Issue by MATTJ0NES** [jsakamoto/BlazorWasmPreRendering.Build#19]
Publishing to a folder fails for me as it tries to crawl pages that from a routing point of view are possible but are not linked to anywhere in my app. Therefore, it errors with the following message:
[ERROR] The HTTP status code was not OK. (it was (500)InternalServerError.)

My routing is similar to the following:

`@page "/"
@page "/calculate/{valuetype}"
@page "/calculate/{valuetype}/from/{value1}"
@page "/calculate/{valuetype}/from/{value1}/to/{value2}"`

The urls I link to have the value1 and value2 parameters determined by the valuetype parameter. So value1 and value2 will be from one predefined list or from another one, depending what the valuetype parameter is.

How does it determine which pages to crawl - should it only be crawling links it finds in my front end or does it take them from somewhere else? And if it takes from somewhere else, how can I make it ignore certain url's that I know aren't meant to work and are not linked to anywhere?

Hope that makes sense and thanks for your work on this!

**Comment by jsakamoto** [comment]
@MATTJ0NES 

> How does it determine which pages to crawl 

It only is crawling links it finds in my front end. It doesn't care what routings are configured in razor files.

[_"Pre-render Blazor WebAssembly on static web hosting at publishing time"_ | dev.to](https://dev.to/j_sakamoto/pre-render-blazor-webassembly-on-static-web-hosting-at-publishing-time-50d8#2nd-crawling)

![](https://res.cloudinary.com/practicaldev/image/fetch/s--Sasmzv9V--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/gq2ur9nqq3u7agi9p5ie.png)

You should see the messages from the "dotnet publish" command in a terminal console, and it should show an error message with stack traces like the following picture when the "500 Internal Server Error" happens.

![](https://raw.githubusercontent.com/jsakamoto/BlazorWasmPreRendering.Build/master/.assets/fig04.http500.png)

Please tell me that error message with stack traces.

And I recommend you try to investigate your app by yourself with the **["Troubleshooting" section](https://github.com/jsakamoto/BlazorWasmPreRendering.Build#troubleshooting)** in the README of this package.

Or else, could you disclose your app's source code?

**Comment by MATTJ0NES** [comment]
Thanks so much. I'd seen the error and knew what links it was trying to crawl and where the errors were, but couldn't see why it was crawling them. However, your response was enough to make look at it differently and I realised that I was writing out incorrect links but then using css to hide them if I didn't want a user clicking on them. The crawler was of course not paying any attention to whether they were visible or not through CSS.
I've gone back and changed my code so rather than showing or hiding with CSS I don't even write them out at all now, which ultimately is better, and means the publish now succeeds.
Thanks again for a great solution.
