### ISSUE TITLE
publish and deploy by action from github - Oryx has failed to build the solution.

### ISSUE THREAD

**Issue by drma-dev** [jsakamoto/BlazorWasmPreRendering.Build#23]
I use static web app on azure and publish through github action.

this is the error i get:
`/var/nuget/blazorwasmprerendering.build/2.0.0-preview.4/build/BlazorWasmPreRendering.Build.targets(58,5): error MSB3073: The command "dotnet "/var/nuget/blazorwasmprerendering.build/2.0.0-preview.4/build/../tools/net6.0/BlazorWasmPreRendering.Build.dll" -a "SD.WEB" -t "SD.WEB.App" --selectorofrootcomponent "#app,app" --selectorofheadoutletcomponent "head::after" -p "/bin/staticsites/ss-oryx/app" -i "/github/workspace/SD.WEB/obj/Release/net6.0/." -m "" -f "net6.0" --serviceworkerassetsmanifest "service-worker-assets.js" -e "Prerendering" --locale "en" -o "IndexHtmlInSubFolders"  -u "" -r "Static" --serverport "5050-5999" --bwapoptionsxorkey """ exited with code 1. [/github/workspace/SD.WEB/SD.WEB.csproj] | 1 | Please build your app locally before publishing. | https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-linux`

my project:
[https://github.com/drma-dev/SD](https://github.com/drma-dev/SD)

**Comment by jsakamoto** [comment]
@drma-dev 
Thank you for reporting!

By the way, I could not open your repository https://github.com/drma-dev/SD. (Please see alo the screen shot below.)

![image](https://user-images.githubusercontent.com/95908/200562932-f41c7a13-a8a8-4fbe-85c3-2285196bd3e0.png)

I guess that repository is private, isn't it? If so, could you invite my GitHub account to the accessible member of that repository?

**Comment by drma-dev** [comment]
now is public

**Comment by jsakamoto** [comment]
@drma-dev Thank you for disclosing your GitHub repository!
I guess you have not yet read the error information message in the following screenshot.

![image](https://user-images.githubusercontent.com/95908/200569824-07712486-aff6-4c68-8073-c6d597c820cd.png)

Could you read that and try to follow the instructions?

**Comment by drma-dev** [comment]
[https://github.com/drma-dev/SD/blob/developer/SD.WEB/Program.cs](https://github.com/drma-dev/SD/blob/developer/SD.WEB/Program.cs)

**Comment by jsakamoto** [comment]
@drma-dev 
Please read the error message and the README of the "BlazorWasmPreRendering.Build" well.

The error message said, "There is no registered service of type 'Blazorise.IThemeGenerator'".

![image](https://user-images.githubusercontent.com/95908/200578804-a5ecc577-1dba-4290-afb0-9a934e962588.png)

And the README of the "BlazorWasmPreRendering.Build" said:
_"This package calls the ConfigureServices() static method (or static local function) inside of your Blazor WebAssembly app when pre-renders it"_

The important thing, your startup code in the `Program.cs` is never called during pre-rendering processing except for the `ConfigureServices()` static method.

Look back at your `Program.cs`, the registration step of the `Blazorise.IThemeGenerator` service to service collection (a.k.a DI container) is in the `ConfigureComponents()` method, not in the `ConfigureServices()` method. Please remind again that the "BlazorWasmPreRendering.Build" doesn't mind the other code except `ConfigureServices()`. So the `ConfigureComponents()` method and service registration of the `Blazorise.IThemeGenerator` service inside that method will never be called during pre-rendering process. Therefore, the error that the missing the `Blazorise.IThemeGenerator` service` caused when the pre-rendering.

All services those are required on the Blazor app must be registerd in the `ConfigureServices()` static method for pre-rendering by the "BlazorWasmPreRendering.Build".

**Comment by drma-dev** [comment]
Sorry, I didn't notice that part of the error.

I adjusted and now there are a lot of errors in the parameters that the pages have. I'll see if I can get around this and get back to you.

**Comment by jsakamoto** [comment]
@drma-dev  Sorry too late since I was busy watching the .NET Conf 2022 that was held this week. (I live in Japan, so I had to wake up at midnight in the Japan Standard Time zone and keep staying up).

By the way, you closed this issue, so does that mean the problem was resolved?

**Comment by drma-dev** [comment]
not exactly. the problem was with a specific component that I was using. the component is abandoned, so there's no point in wasting time trying to solve it. I just removed it and I'll try to solve it another way.

**Comment by drma-dev** [comment]
@jsakamoto 
but if you want to try to find out, the problem is here
[https://github.com/Blazored/SessionStorage/blob/0a1a428dfe389ac03a619a9f76409b6c47bd13ac/src/Blazored.SessionStorage/BrowserStorageProvider.cs](https://github.com/Blazored/SessionStorage/blob/0a1a428dfe389ac03a619a9f76409b6c47bd13ac/src/Blazored.SessionStorage/BrowserStorageProvider.cs)

**Comment by jsakamoto** [comment]
@drma-dev  Thank you for replying, I got it.

It is important to understand that the "BlazorWasmPreRendering.Build" implements the pre-rendering feature by a kind of hacking that **executes your Blazor Wasm app in a server-side process (not in a web browser process) as a Blazor Server app forcibly with some magics**.

Therefore everyone who wants to pre-render with the "BlazorWasmPreRendering.Build" is not allowed to place any JavaScript interop code in an "OnInitialized" or "OnInitializedAsync" lifecycle method regardless of whether directly or indirectly (because there is no JavaScript engine in a web server!). Instead, they have to put a JavaScript interop code in an "OnAfterRenderAsync" lifecycle method. 
(Please see also:  https://learn.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet#prerendering )

Or else, ensure to use a JavaScript interop code in an "OnInitialized" or "OnInitializedAsync" lifecycle method only when it is not running on a pre-rendering process. You can detect whether it is running on pre-render process or not by referencing a hosting environment name to check if it is "Prerendering" or not.
(Please see also: https://github.com/jsakamoto/BlazorWasmPreRendering.Build#hosting-environment)

**Comment by drma-dev** [comment]
so this pre-rendering causes OnInitializedAsync to be called twice? and I only need to use javascript the second time?

**Comment by jsakamoto** [comment]
> so this pre-rendering causes OnInitializedAsync to be called twice?

Uh, almost yes.

1. First, OnInitializedAsync is called in a server-side pre-rendering process with the "Prerendering" hosting environment name.
2. Next, OnInitializedAsync is called again in a web browser process after all of the Blazor Wasm contents are loaded on the web browser with the "Production" hosting environment name.
3. Finally, OnAfterRenderingAsync is called in the same web browser process. (OnAfterRenderingAsync is never called in a server-side pre-rendering process.)

Please be careful to understand where your code is running on.

> and I only need to use javascript the second time?

Yes, you can only use a JavaScript interop code the second time calling of OnInitializedAsync, or anywhere later in that second calling. (To say the list above, you can use javascript at 2 and 3 of the list because step 1 of the list above is running on a server, not a browser.)

But please remember that putting a JavaScript interop code to OnAfterRenderAsync, not to OnInitializedAsync, is standard practice on a usual Blazor Server programming.

**Comment by drma-dev** [comment]
> But please remember that putting a JavaScript interop code to OnAfterRenderAsync, not to OnInitializedAsync, is standard practice on a usual Blazor Server programming.

I've always read this, but I've always ignored it. haha ha

it's because at the same time I get data from an api, I use it to save it in the browser cache (which is through the use of javascript).

so it can be said that it would also be recommended to access the api only in OnAfterRenderAsync?

**Comment by jsakamoto** [comment]
> so it can be said that it would also be recommended to access the api only in OnAfterRenderAsync?

From the viewpoint of only accessing a web API, I can't say yes.
Because, usually accessing a web API in a server process (ex., accessing a web API in OnInitializedAsync) will not cause something wrong.
But in some particular scenarios like you said (access a web API and store the results of it to browser's storage via JavaScript interop), it might be better to make those codes be put in OnAfterRenderAsync in a lump.

**Comment by drma-dev** [comment]
I'm trying to solve it with IMemoryCache, if it doesn't work, then I'm going to use OnAfterRenderAsync .

**Comment by drma-dev** [comment]
@jsakamoto 
worked perfectly. and it still has the advantage of having an expiration time.

note: I tried with core 7 and it didn't work. I think you need to update this.

**Comment by jsakamoto** [comment]
@drma-dev 
> note: I tried with core 7 and it didn't work. I think you need to update this.

In my test cases, the "BlazorWasmPreRendering.Build" has been working well even on .NET 7.
(ex. https://github.com/jsakamoto/awesome-blazor-browser)

I've no idea about that due to there is no information on how it didn't work, such as error messages.

**Comment by drma-dev** [comment]
```
Getting http://127.0.0.1:5050/...
  Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   ---> System.TimeoutException: The operation was canceled.
   ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
   ---> System.Net.Sockets.SocketException (125): Operation canceled
     --- End of inner exception stack trace ---
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
     at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
     at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
     --- End of inner exception stack trace ---
     at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
     at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
     at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
     at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
     --- End of inner exception stack trace ---
     --- End of inner exception stack trace ---
     at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
     at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
     at Toolbelt.Blazor.WebAssembly.PreRendering.Build.StaticlizeCrawler.SaveToStaticFileAsync(ValueTuple`3 args) in C:\Projects\My\Blazor\PreRendering\BlazorWasmPreRendering.Build\StaticlizeCrawler.cs:line 120
     at Toolbelt.Blazor.WebAssembly.PreRendering.Build.StaticlizeCrawler.SaveToStaticFileAsync() in C:\Projects\My\Blazor\PreRendering\BlazorWasmPreRendering.Build\StaticlizeCrawler.cs:line 81
     at Toolbelt.Blazor.WebAssembly.PreRendering.Build.Program.PreRenderToStaticFilesAsync(CommandLineOptions commandLineOptions, BlazorWasmPrerenderingOptions prerenderingOptions) in C:\Projects\My\Blazor\PreRendering\BlazorWasmPreRendering.Build\Program.cs:line 56
     at Toolbelt.Blazor.WebAssembly.PreRendering.Build.Program.Main(String[] args) in C:\Projects\My\Blazor\PreRendering\BlazorWasmPreRendering.Build\Program.cs:line 28
     at Toolbelt.Blazor.WebAssembly.PreRendering.Build.Program.<Main>(String[] args)
  Aborted (core dumped)
```

**Comment by jsakamoto** [comment]
@drma-dev 
 Thanks! I'm not sure why the pre-rendering server process didn't respond to requests at this time, but any way, I'll investigate it.

**Comment by jsakamoto** [comment]
@drma-dev [Progress report] I'm investigating the problem that your site could not prerender with the "BlazorWasmPreRendering.Build" after upgrade to .NET7. Unfortunately, it has been a difficult task. I can't say anything about the root reason now, but I think that there is a possibility the Azure static web app's authentication library might involve with this problem. I continue to try to resolve this problem.

**Comment by jsakamoto** [comment]
@drma-dev 

I found the reason why pre-rendering failed on your app with .NET 7.

Your app tries to fetch authenticated user data from the API endpoint "/.auth/me" at the startup of pre-rendering.

However, the pre-rendering environment is not the same as a release environment. So there is nobody who catches and responds to the API endpoint "/.auth/me". Instead, the pre-rendering environment will try to return the bootstrap page of the app itself as a fallback page to the request of "/.auth/me".

This situation caused an infinite loop like the below during pre-rendering:

Start pre-rendering of "/" -> Fetch "/.auth/me" at startup -> Start pre-rendering of "/.auth/me" -> Fetch "/.auth/me" at startup -> Start pre-rendering of "/.auth/me"...

Finally, pre-rendering timed out and failed.

Fortunately, I also found a workaround for this problem. I implemented it and sent it to you as a pull request.

- https://github.com/drma-dev/SD/pull/2

For the detail of the workaround, please see the comment on that pull request above.

**Comment by drma-dev** [comment]
I don't think I was ever going to find that out. I'm bad at authentication.

**Comment by drma-dev** [comment]
@jsakamoto  with this new update is it still necessary to make that workaround you made?

**Comment by jsakamoto** [comment]
@drma-dev 
No, actually, the workaround I sent you as a pull request is no longer needed on the latest version of the "BlazorWasmPreRendering.Build". Thank you for keeping to watch this project.
