### ISSUE TITLE
Add support for .NET 8

### ISSUE THREAD

**Issue by danroth27** [jsakamoto/BlazorWasmPreRendering.Build#29]
Looks like only .NET 5, 6, & 7 are currently supported: https://github.com/jsakamoto/BlazorWasmPreRendering.Build/blob/master/BlazorWasmPreRendering.Build/build/BlazorWasmPreRendering.Build.targets#L10-L12

.NET 8 previews are now available, so it would be great to add .NET 8 support.

**Comment by jsakamoto** [comment]
@danroth27 Sure, I'll do it as soon as I can. Thank you for letting me know!

**Comment by jsakamoto** [comment]
@danroth27 I released the new version that supports .NET 8.

- https://www.nuget.org/packages/BlazorWasmPreRendering.Build/2.0.0-preview.8#release-body-tab

Could you try it out? Thanks!

**Comment by danroth27** [comment]
Thanks for the quick fix and release! We were able to successfully update our https://aka.ms/blazor/quickgrid site to use the new package with .NET Preview 2.

**Comment by danroth27** [comment]
> I'm currently working on developing the "Blazing Story", a clone of the "Storybook" built on Blazor

That's super cool! Liked :heart: on Twitter.
