### ISSUE TITLE
Visual Studio Publish results in 404 error for images in webp format

### ISSUE THREAD

**Issue by fingers10** [jsakamoto/BlazorWasmPreRendering.Build#39]
Hi @jsakamoto 

I'm using BlazorWasmPreRendering.Build - 3.1.0-preview.4 and did a folder publishing of [ilovedotnet](https://github.com/ILoveDotNet/ilovedotnet) repo in Visual Studio and deployed to IIS. When I loaded it in browser the images are not displayed and shows 404 error. The images are in `webp` format.

The images in `png` format are loaded but `webp` is not:

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/43729469/9ab830e0-98f1-4872-91cf-6304aba2640f)

The images are downloaded and here is the source tab screenshot from browser.

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/43729469/977b2613-5a25-4f57-b841-945b2dfb0959)

Here is the console error output from browser:

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/43729469/7b2496ff-1b83-49e8-bdaa-b5901bc12a45)

But this works in GitHub publish. Looks like something is wrong when Published using Visual Studio. Please assist on what I'm missing,

Thanks,
Abdul Rahman

**Comment by jsakamoto** [comment]
@fingers10 
It must not be the problem of this package. I guess that your IIS server could not serve any .webp files.

**Comment by fingers10** [comment]
Ah ha is it?? Lemme check my IIS and keep you posted.

**Comment by jsakamoto** [comment]
@fingers10 For example, if you put the `web.config` file that has the below contents to the IIS's apprication root folder,

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <mimeMap fileExtension=".webp" mimeType="image/webp" />
    </staticContent>
  </system.webServer>
</configuration>
```

then the .webp image files will be served, I believe.

If there is already a `web.config` file, you should insert one line `<mimeMap fileExtension=".webp" mimeType="image/webp" />` under the `configuration` > `system.webServer` > `staticContent` node of the `web.config` file.

You can also do that via the IIS Manager GUI like below.

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/61bc1abb-3733-43fc-bf99-d3f4d76c0cf3)

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/94fe7f2f-bf77-4437-b9b5-a5437093f10d)

**Comment by fingers10** [comment]
@jsakamoto perfect it works. Thanks for teaching. I learn't something new today,
