### ISSUE TITLE
Partially pre-rendering

### ISSUE THREAD

**Issue by pmeems** [jsakamoto/BlazorWasmPreRendering.Build#5]
This is not a real issue, more a question.
I have an Azure Static WebApp with Azure Functions and I'm investigating if your package will work in my scenario.
I tried it and my index and counter pages are pre-rendered successful, but with my FetchData page the package wants to pre-render the data as well. But during publish the Function is not up yet so it generates an error message.
And I don't want to pre-render the data. 

Can this package pre-render all static data and leave the dynamic data as is?
If so how do I do this?

My code is at https://github.com/pmeems/BlazorWasmTailwind and my static website runs at https://purple-meadow-079619e03.azurestaticapps.net/

**Comment by jsakamoto** [comment]
If your code can detect that it is running on the pre-rendering process or not, is it useful?

For example, if the `IWebAssemblyHostEnvironment.Environment` can return "PreReindering" while pre-rendering process, you may be able to avoid API calls like this.

```csharp
@inject IWebAssemblyHostEnvironment HostEnv
...
@code {
    ...
    protected override async Task OnInitializedAsync()
    {
        try
        {
            // 👇 "If the code is running on the pre-rendering process, then don't call APIs."
            if (HostEnv.Environment == "PreRendering") return;

            Forecasts = await _http.GetFromJsonAsync<WeatherForecast[]>("/api/WeatherForecast") ?? new WeatherForecast[] { };
        }

```


Currently, the "BlazorWasmPreRendering.Build" can't provide information on whether it is running on the pre-rendering process or not.
But recently, I'm considering implementing that feature.

**Comment by jsakamoto** [comment]
@pmeems 

I did it.

- https://www.nuget.org/packages/BlazorWasmPreRendering.Build/1.0.0-preview.13.0

The document is following.

- https://github.com/jsakamoto/BlazorWasmPreRendering.Build#hosting-environment

I hope this feature is helpful for you.

**Comment by pmeems** [comment]
WOW!
Just made the suggested changes and updated the package and now it is working as I expect!

Good job!

I also have a question about sitemaps, but will create a new issue for that.

**Comment by pmeems** [comment]
I might have closed this question too soon.
After deploying to Azure Static Web App, I can't see the pre-rendering starting. Or perhaps I should update my yaml: https://github.com/pmeems/BlazorWasmTailwind/blob/main/.github/workflows/azure-static-web-apps-purple-meadow-079619e03.yml Perhaps my `output_location: "wwwroot"` should be updated, but I'm not sure.

I would really appreciate it if you would suggest how to get this working on Azure Static Web App.

**Comment by pmeems** [comment]
Sorry for the confusion. I must read better.
I just did everything that was in the updated documentation, not realizing it wasn't all necessary.
After removing `<BlazorWasmPrerenderingEnvironment>Production</BlazorWasmPrerenderingEnvironment>` Azure deploys correctly as well.
