### ISSUE TITLE
<HeadContent> rendered twice when Blazor runs

### ISSUE THREAD

**Issue by TehGM** [jsakamoto/BlazorWasmPreRendering.Build#7]
I use `<HeadContent>` on every page to control what appears there. This is pre-rendered absolutely correctly, and saved between `%%-PRERENDERING-HEADOUTLET-BEGIN-%%` and `%%-PRERENDERING-HEADOUTLET-END-%%` comments. All great, this library works and is so far the easiest solution I've found.

Once I serve the website, open in browser, F12 and look at DOM, these tags are rendered twice, and the pre-rendered ones do not update on page change. This is of course understandable, due to how .NET 6 `<HeadContent>` works.

With most bots it'll be no issue but some like google actually wait for WASM to load, so I was wondering if there is any recommended way to remove the pre-rendered head content. I do not mind if it is something that I have to call myself or something - and I actually expect that it'd need to be approached this way. However having even that kind of solution would be great - if it is possible at all, of course.

**Comment by jsakamoto** [comment]
Sorry to late!

I fixed this issue and I published new version of this package.

- https://www.nuget.org/packages/BlazorWasmPreRendering.Build/1.0.0-preview.15.0

Please try it out ;)

**Comment by TehGM** [comment]
Hey, just tested it - doing so actually helped me spot a bug I introduced, too. :D 

It seems to work pretty well. Cheers, you the man!
