### ISSUE TITLE
Prerendering doesn't render Meta and Link tags

### ISSUE THREAD

**Issue by fingers10** [jsakamoto/BlazorWasmPreRendering.Build#9]
I'm having the below content in my `Index.razor`. I'm using `<Meta>` and `<Link>` from [Toolbelt.Blazor.HeadElement](https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement) Nuget

```razor
<Meta Property="description" Content="@Description" />
<Meta Property="keywords" Content="Keywords" />
<Meta Property="url" Content="@BaseUrl" />
<Meta Property="identifier-URL" Content="@BaseUrl" />
<Meta Property="og:site_name" Content="@Title" />
<Meta Property="og:type" Content="website" />
<Meta Property="og:title" Content="@Title" />
<Meta Property="og:description" Content="@Description" />
<Meta Property="og:url" Content="@BaseUrl" />
<Meta Property="twitter:card" Content="summary" />
<Meta Property="twitter:title" Content="@Title" />
<Meta Property="twitter:description" Content="@Description" />
<Meta Property="twitter:url" Content="@BaseUrl" />
<Link Rel="sitemap" Href="@($"{BaseUrl}sitemap.xml")" />
<Link Rel="alternate" Href="@($"{BaseUrl}atom.xml")" />
<Link Rel="alternate" Href="@BaseUrl" />
<Link Rel="alternate" Href="@BaseUrl" />
<Link Rel="canonical" Href="@BaseUrl" />
<Link Rel="index" Href="@BaseUrl" />
<HeadContent>
    @(new MarkupString(
    $@"<script type=""application/ld+json"">
    {{
        ""@context"": ""https://schema.org"",
        ""@type"": ""WebSite"",
        ""publisher"": {{
            ""@type"": ""Organization"",
            ""name"": ""{Title}"",
            ""url"": ""{BaseUrl}"",
            ""logo"": {{
                ""@type"": ""ImageObject"",
                ""url"": ""{BaseUrl}favicon.ico"",
                ""width"": 16,
                ""height"": 16
            }}
        }},
        ""url"": ""{BaseUrl}"",
        ""mainEntityOfPage"": {{
            ""@type"": ""WebPage"",
            ""@id"": ""{BaseUrl}""
        }},
        ""description"": ""{Description}""
    }}
    </script>"))
</HeadContent>
```

After prerendering, `index.html` contains only content inside `<HeadOutlet>`. Remaining `<Meta>` and `<Link>` tags are not available in `index.html`.

**Comment by jsakamoto** [comment]
@fingers10 

Unfortunately, I could not reproduce that problem in my simple test project.

Could you make a minimal sample project to reproduce the problem and attach it as a single zip file to this thread?

**Comment by jsakamoto** [comment]
@fingers10 Thank you for investigating the problem and letting me know the details!

I will consider how I can support that "Razor Class Library" scenario.

**Comment by jsakamoto** [comment]
@fingers10 Since I implemented some improvements in these months, so the combination of the latest version of both the "Toolbelt.Blazor.HeadElement" and the "BlazorWasmPreRendering.Build" should work expectedly, even on the "Razor Class Library" scenario that you told me.

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/7.2.0
- https://www.nuget.org/packages/BlazorWasmPreRendering.Build/1.0.0-preview.24.0

I hope these versions work fine as you expected without adding a package reference to the "Toolbelt.Blazor.HeadElement" package into a Blazor application startup project.

**Comment by fingers10** [comment]
@jsakamoto This works fine now. This can be closed now.
